export const PRODUCT_MANAGEMENT = 'PRODUCT_MANAGEMENT';
export const FILTERCAKE_MANAGEMENT = 'FILTERCAKE_MANAGEMENT';
export const RAWMATERIAL_MANAGEMENT = 'RAWMATERIAL_MANAGEMENT';
export const PRODUCTSERY_MANAGEMENT = 'PRODUCTSER_MANAGEMENT';
export const MEMBER = 1;
export const MANAGER = 3;
export const OWNER = 7;