export const PRODUCT_MANAGEMENT = 'PRODUCT_MANAGEMENT';
export const FILTERCAKE_MANAGEMENT = 'FILTERCAKE_MANAGEMENT';
export const RAWMATERIAL_MANAGEMENT = 'RAWMATERIAL_MANAGEMENT';
export const MEMBER = 2;
export const MANAGER = 1;
export const OWNER = 0;